file = open("name.txt" , "w")
file.write("This is the new line.\n")
file.write("Damn! \nwrite function just deletes everything from the file and then rewrites new thing on it.")
file.write("\n No! It does not rewrite everytime a new function is called. Rather it rewrites everytime a file is opened in write only mode. ")
file.close()
file = open("file.py", "w")
file.write("print(\"O ma gu turu lob\")")
file.close()
file = open("file.cpp","w")
file.write("#include<iostream>")
file.write("\nusing namespace std;")
file.write("int main()")
file.write("{\ncout << \"o ma gu turu lob\";\n}")
file.close()